### ISSUE TITLE
error when i try to open an url queries.

### ISSUE THREAD

**Issue by CavalcanteLeo** [ddprrt/connect-php#5]
```
   if(req.url.endsWith('.php')){
      ...
   }
```

it doens't work when the url has query, eg: localhost:9000/index.php?a=b;

**Comment by ddprrt** [comment]
The PR referred in #4 should fix this. Maybe @mattxo is up for working on it?

**Comment by mattxo** [comment]
Yup. @ddprrt has merged the PR, should be good to go now @CavalcanteLeo :)

**Comment by ddprrt** [comment]
Published v0.0.2 at NPM. Thanks @mattxo for looking into this! Very much appreciated :+1:
